;**************************************************;
;          Seeed Studio XIAO ESP32-S3               ;
;          with ili9341 0x2046 TFT 2.4"             ;
;               - D1-mini-esp32 board               ;
;               - ili9341 TFT                       ;
;               - xpt2046 touch controller          ;
;***************************************************;
;    
;    JWG: Settings for HARC1P0
;    ;    Label      GPIO   ILI9341
;    ;    =======   =====  ========
;    ;    TS_CS     = 44   CS2-10  Touch Screen Chip x2046 select (TOUCH_CS)
;    ;    TFT_CS    = 05   CS1-09  TFT Display Screen Select
;    ;    MISO      = 08      -08
;    ;    MOSI      = 09      -04
;    ;    TFT_LED   = 04      -07
;    ;    DC        = 43      -06
;    ;    RST       = 06      -05
;    ;    CLK       = 07      -03
;    ;
;    ; Set ARDUINO_USB_CDC_ON_BOOT = 0
;
;
[env:seeed_xiao_esp32s3]
extends = arduino_esp32s3_v2, flash_8mb
board = seeed_xiao_esp32s3
board_build.arduino.memory_type = qio_opi

build_flags =
    -D HASP_MODEL="ESP32-S3 Devkit C"
    ${arduino_esp32s3_v2.build_flags}
    ${esp32s3.no_ps_ram}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_XIAO_ESP32S3
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
    ${env.build_flags}
    -Wall
    -Wextra

;region -- TFT_eSPI build options ------------------------
    ${lcd.ili9341}
    ${touch.xpt2046}
   -D TFT_DC=43
   -D TFT_CS=05
   -D TFT_RST=06        ; RST
   -D TFT_BCKL=04       ; None, configurable via web UI (e.g. 21)
   -D TOUCH_CS=44       ; (can also be 22 or 16)
   -D TFT_SCLK=07
   -D TFT_MOSI=09
   -D TFT_MISO=08
;endregion

lib_deps =
    ${arduino_esp32s3_v2.lib_deps}
    ${lovyangfx.lib_deps}
    ${tft_espi.lib_deps}
